### ISSUE TITLE
function node_set_pollutant does not work properly.

### ISSUE THREAD

**Issue by jlonghku** [OpenWaterAnalytics/swmm-python#104]
Hi, I just tested the function node_set_pollutant in the package swmm-toolkit and found it does not change the nodes' value of pollutants (node_get_pollutant). But the function link_set_pollutant works well I think. Is there any problem with the function?

**Comment by karosc** [comment]
Are you able to post a model and code that demonstrates this problem? Check [this PR discussion](https://github.com/OpenWaterAnalytics/swmm-python/pull/94) for information on pollutant functions. One of my issues was that a node needs to be specified in the [swmm treatment section for pollutant setter to work](https://github.com/OpenWaterAnalytics/swmm-python/pull/94#issuecomment-1013951491)

**Comment by jlonghku** [comment]
It works after I specifically set up the treatment formula section of that node, many thanks for your kind reply!
