### ISSUE TITLE
Packaging and distribution

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/swmm-python#20]
[networkx](https://github.com/networkx) is an example of a python library that combines multiple namespace packages into one distribution package. Perhaps it can serve as a template for `swmm-python`.

**Comment by michaeltryby** [comment]
The current namespace package layout is proving difficult to work with. The thinking was that it would be nice to have the `swmm.output` and `swmm.toolkit` packages living in the same namespace but installable  separately. For example, reg testing only requires `swmm.output`.  Most users, however, will probably be using them together so they aren't going to care. 

Separate namespace packages means 2x the number of wheels. Building all those wheels for all the different python versions and platforms could become a headache.   

Separate wheels means separate entries in the pypi index so we can't host the package under the `swmm-python` name that we are currently squatting on.

**Comment by michaeltryby** [comment]
@bemcdonnell any thoughts?

**Comment by bemcdonnell** [comment]
@michaeltryby, it's a fair point to bring up.  On one hand, 90% of the users will probably leverage both parts.  However, CI systems would probably only need the output API. I also hear the point about separating concerns.  But in the end, if it were up to me, much like `networkx`, I'd keep these in a single package/distro.  NetworkX ships with different algorithms and graph analysis features. Technically these are specific methods that could be separated off into their own packages.  However, their use-cases are so common that the come with the standard lib.

So my [silly] question - with setuptools, is there any way to install part of a package?
