### ISSUE TITLE
error when running python setup.py file

### ISSUE THREAD

**Issue by jennwuu** [OpenWaterAnalytics/swmm-python#21]
@michaeltryby 

Hi! Totally new to SWIG in general, so apology in advance if I asked something really simple/silly, but I tried following the readme to setup swmm-python, but I'm stuck with the following errors:

swmm/toolkit/toolkit_wrap.c(3310): error C2065: 'SWMM_ProjectHandle': undeclared identifier
swmm/toolkit/toolkit_wrap.c(3310): error C2065: 'arg1': undeclared identifier
swmm/toolkit/toolkit_wrap.c(3310): error C2059: syntax error: ')'
swmm/toolkit/toolkit_wrap.c(3311): error C2065: 'SWMM_ProjectHandle': undeclared identifier
swmm/toolkit/toolkit_wrap.c(3311): error C2146: syntax error: missing ';' before identifier 'retval1'
swmm/toolkit/toolkit_wrap.c(3311): error C2065: 'retval1': undeclared identifier
swmm/toolkit/toolkit_wrap.c(3316): error C2065: 'retval1': undeclared identifier
swmm/toolkit/toolkit_wrap.c(3316): warning C4047: '=': 'int' differs in levels of indirection from 'void *'
swmm/toolkit/toolkit_wrap.c(3317): error C2065: 'arg1': undeclared identifier
swmm/toolkit/toolkit_wrap.c(3317): error C2065: 'retval1': undeclared identifier
swmm/toolkit/toolkit_wrap.c(3317): warning C4047: '=': 'int' differs in levels of indirection from 'int *'
swmm/toolkit/toolkit_wrap.c(3320): warning C4013: 'swmm_alloc_project' undefined; assuming extern returning int
swmm/toolkit/toolkit_wrap.c(3320): error C2065: 'arg1': undeclared identifier
swmm/toolkit/toolkit_wrap.c(3327): error C2065: 'retval1': undeclared identifier
swmm/toolkit/toolkit_wrap.c(3337): error C2065: 'SWMM_ProjectHandle': undeclared identifier
swmm/toolkit/toolkit_wrap.c(3337): error C2065: 'arg1': undeclared identifier
swmm/toolkit/toolkit_wrap.c(3337): error C2059: syntax error: ')'
swmm/toolkit/toolkit_wrap.c(3338): error C2065: 'SWMM_ProjectHandle': undeclared identifier

These are the steps I used:
1. Clone owa swmm develop branch
2. Built the swmm following the instructions from owa swmm
3. Copied header files (swmm5.h and toolkitAPI.h) to include folder within \swmm-python\toolkit\swmm\toolkit
4. Copied swmm5.dll, swmm5.exp, swmm5.lib to lib folder within \swmm-python\toolkit\swmm\toolkit
5. tried python setup.py build but got the following errors
 
Is SWIG trying to find the SWMM_ProjectHandle within the header files?

**Comment by michaeltryby** [comment]
@jennwuu sounds like you did everything correctly. Use the feature-reentrancy branch instead of develop and it should work.

**Comment by michaeltryby** [comment]
@jennwuu I updated the build instructions.
