### ISSUE TITLE
swmm.output SMO_sys enum type is missing from python 37 whl

### ISSUE THREAD

**Issue by TongZhai** [OpenWaterAnalytics/swmm-python#32]
I just installed the latest swmm.output whl (swmm.output-0.4.0.dev0-cp37-cp37m-win_amd64.whl), it install correctly, but failed at runtime. It is missing the SMO_sys enum type, I saw SMO_link, SMO_node, and SMO_subcatch, but didn't see SMO_sys type

**Comment by michaeltryby** [comment]
@TongZhai I patched this bug. I noticed that the UI code uses library constants directly to build metadata lookup. We should migrate away from doing this and instead use the Enum classes provided in the `output.py` wrapper. By the way, the package also provides a simplified API for looking up metadata.
