### ISSUE TITLE
sample code for output

### ISSUE THREAD

**Issue by mel-meng** [OpenWaterAnalytics/swmm-python#34]
I was able to download and install the following,
swmm.output-0.4.0.dev1-cp37-cp37m-win_amd64.whl

Not sure how to get started, tried the following from the test and got an error.

![image](https://user-images.githubusercontent.com/2023246/80389199-c6252e80-8878-11ea-92dd-a18a66ff7cc3.png)

**Comment by prasanna310** [comment]
Hi Mel-meng,
I believe the developers have changed the arrangements a bit, programmatically speaking. I was able to get it to work by doing:
```
from swmm.output import output as smo
p_handle = smo.init()
smo.open(p_handle, 'path/to/.out')
```
Hope that helps.

**Comment by mel-meng** [comment]
from swmm.output import output as smo

Fixed it. 

Thanks!

**Comment by mel-meng** [comment]
I have a few more questions?
* What is returned when getxxxresult is called?
* How can I convert the time integer to time stamp?

Thanks.

**Comment by prasanna310** [comment]
- getxxxresults returns a list of values.

- Integers represent timesteps. If you are reporting result at 15 minutes, and you simulation starts from 00:00 am, then 00:15am would be 1, and 00:30am would be 2 and so on. (May be the developers can clarify if I am wrong)

**Comment by mel-meng** [comment]
thanks @prasanna310. One more question, What is the difference between getxxxresult and getxxxseries?

**Comment by prasanna310** [comment]
I have personally only used getxxseries. But looking at the inputs required for getxxxresult, it probably only returns on value, not a list or series.

**Comment by DJHostetler** [comment]
I second the thought that it would be helpful to have better documentation for the different results functions. Any thoughts on how you tell when you run getnoderesult or getlinkresult what the output variables actually are?

**Comment by cbuahin** [comment]
This work is ongoing so I suggest you look at the tests to get a sense for how things work. 

https://github.com/OpenWaterAnalytics/swmm-python/blob/dev/swmm-toolkit/tests/test_output.py

**Comment by DJHostetler** [comment]
That is helpful @cbuahin - thank you for addressing both of my questions.
