### ISSUE TITLE
swmm.toolkit open input file error

### ISSUE THREAD

**Issue by mel-meng** [OpenWaterAnalytics/swmm-python#35]
Here is the input file:
https://github.com/mel-meng/SewerAnalysis/blob/master/bugs/data/swmm.toolkit.bug.inp

Running the same code on the example1.inp works fine.

Here is how to reproduce the bug:
https://github.com/mel-meng/SewerAnalysis/blob/master/bugs/swwm.toolkit%20error%20in%20input%20file.ipynb

I installed the latest release python 3.7 64bit *.whl.
![image](https://user-images.githubusercontent.com/2023246/80915842-bf883280-8d22-11ea-8c99-f9816ff3c3d2.png)

thanks.

Mel

**Comment by abhiramm7** [comment]
@mel-meng I am closing this issue for now. Please reopen it if this issue is unresolved.
