### ISSUE TITLE
uploading wheel to pypi

### ISSUE THREAD

**Issue by lrntct** [OpenWaterAnalytics/swmm-python#53]
Is there any plan to upload the last packages to the Python Package Index? The package already has an [entry](https://pypi.org/project/swmm-python/). This will facilitate testing and integration with other packages.

**Comment by michaeltryby** [comment]
Hey @lrntct! Good to hear from you. We do plan on uploading to pypi when we make our release. Until then wheels are available in development pre-releases found here: 

https://github.com/OpenWaterAnalytics/swmm-python/releases

And as artifacts for every build performed on our CI system found here: 

https://github.com/OpenWaterAnalytics/swmm-python/actions

**Comment by michaeltryby** [comment]
Hey @lrntct. I wanted to provide you with a quick update.  We have made our release and wheels have been uploaded to [pypi](https://pypi.org/project/swmm-toolkit/) as per your request.
