### ISSUE TITLE
import broken after merging PR61

### ISSUE THREAD

**Issue by andredaa** [OpenWaterAnalytics/swmm-python#65]
Hej swmm-python team, 
i had been compiling swmm-python from source , using the dev-workflow branch (PR61) yesterday. 
Everything worked fine. 
Now after the merge, compiling from the dev branch, I get an import error when trying to import the output module.

I didnt change anything in my code , so i fear that some little error occured from the merge?

Best regards :)
Andre

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/swmm_toolkit-0.8.1-py3.6-linux-x86_64.egg/swmm/toolkit/output.py", line 20, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libswmm-output.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from make_result_geojson import get_result_geojson
  File "/app/make_result_geojson.py", line 4, in <module>
    from swmm.toolkit import output, shared_enum, output_metadata
  File "/usr/local/lib/python3.6/dist-packages/swmm_toolkit-0.8.1-py3.6-linux-x86_64.egg/swmm/toolkit/output.py", line 23, in <module>
    _output = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/swmm_toolkit-0.8.1-py3.6-linux-x86_64.egg/swmm/toolkit/output.py", line 22, in swig_import_helper
    return importlib.import_module('_output')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_output'
```

**Comment by michaeltryby** [comment]
Hey @andredaa it looks like you built the swmm-toolkit as an egg. Try building and installing it as a wheel and it should work.

**Comment by andredaa** [comment]
hmm. I am installing it this way: 
# build swmm-python from source [installation buggy, PR pending]
RUN git clone https://github.com/OpenWaterAnalytics/swmm-python.git
RUN apt-get install swig -y
WORKDIR /app/swmm-python
RUN git submodule init
RUN git submodule update
WORKDIR /app/swmm-python/swmm-toolkit
RUN python3 setup.py build
RUN python3 setup.py install

actually because installing it from pip always resulted in an issue. Something with PEP517. 
I thought it was this issue: https://github.com/OpenWaterAnalytics/pyswmm/issues/270

so - to bypass it , i checked out the dev-workflow branch and build / installed it via the setup.py

but now - i am a bit lost. How do i make a wheel from it? Sorry :p

**Comment by andredaa** [comment]
a. i guess using this. https://github.com/OpenWaterAnalytics/swmm-python/blob/dev/swmm-toolkit/tools/build-wheels.sh

**Comment by michaeltryby** [comment]
`python setup.py install`
  creates an egg

`pip install wheel`
`python setup.py bdist_wheel` 
creates a wheel

**Comment by michaeltryby** [comment]
@andredaa Looks like you are building in a container? If you are building for yourself you don't need to. 

I set up the build to generate manylinux2014 wheels. That's what build-wheels.sh is for. You can find them here. 
https://github.com/OpenWaterAnalytics/swmm-python/actions/runs/621880944
Just click on "artifacts" to download. It would be super cool if you could test the manylinux wheel and let me know if you works for you. Thanks!

**Comment by jennwuu** [comment]
@michaeltryby we should update wiki to provide documentation if anyone wants to build .whl

**Comment by andredaa** [comment]
Perfect this whl
pip install swmm_toolkit-0.8.1-cp38-cp38-manylinux2014_x86_64.whl
works perfectly on my Manjaro (Arch linux) machine. trying the docker now.
Also makeing a wheel via python setup.py bdist_wheel  worked. Installation of that wheel also worked.

**Comment by michaeltryby** [comment]
@andredaa That is awesome thanks so much!

**Comment by andredaa** [comment]
also works in the docker :)
This is awesome, yes!! 
But don't thank me. We thank you!!! 
SWMM seems to have a wonderful community and is so well documented. (besides being incredibly powerful of course).

**Comment by jennwuu** [comment]
@andredaa ooooo interesting are you running a lot of models using docker?

**Comment by andredaa** [comment]
@jennwuu  : no, it's our first one :)  - we are building map-based simulation platforms to support urban planning processes. For this the user sees a 3D model of the planned neighborhood and can test different subcatchment draining setups on a set of storms. The planning goal is to optimize for runoff. I am sure my colleaque, who planned the application would be happy to discuss with you the details  (i am just the codemonkey). she is a great fan of swmm and admirer of the epa-swmm-crew. :) Reading your website it sounds like you guys would like each other :)

**Comment by andredaa** [comment]
oh , i closed the issue , since everything works :)

**Comment by jennwuu** [comment]
oh my gosh that is sooo cool! I would love to chat about it more. Super duper awesome project!
