### ISSUE TITLE
Fix aenum issue

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/swmm-python#72]
Aenum, a dependency to swmm-toolkit, was recently updated. The update broke a feature we rely on. 

swmm-toolkit v0.8.1 needs aenum v2.2.4 but this version is not specified in the setup.py file. 

The dev branch contains bug fix for `shared_enum.py` to get around the problem in aenum 3.0.

**Comment by jennwuu** [comment]
Can we update requirements.txt file for aenum==2.2.6 and re-release swmm-toolkit v0.8.1?

**Comment by jennwuu** [comment]
@michaeltryby Can we close this issue?

**Comment by michaeltryby** [comment]
Yeah sounds good!
