### ISSUE TITLE
import of binary fails

### ISSUE THREAD

**Issue by lrntct** [OpenWaterAnalytics/swmm-python#74]
Hi,

Importing pyswmm fails with the following error:

```
In [1]: import pyswmm
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2215b2c7feca> in <module>
----> 1 import pyswmm

~/miniforge3/envs/hidrologia/lib/python3.8/site-packages/pyswmm/__init__.py in <module>
      9 
     10 # Local imports
---> 11 from pyswmm.links import Link, Links
     12 from pyswmm.lidcontrols import LidControls, LidControl
     13 from pyswmm.lidgroups import LidGroups, LidGroup, LidUnit

~/miniforge3/envs/hidrologia/lib/python3.8/site-packages/pyswmm/links.py in <module>
     10 
     11 # Local imports
---> 12 from pyswmm.swmm5 import PYSWMMException
     13 from pyswmm.toolkitapi import LinkParams, LinkResults, LinkPollut, LinkType, ObjectType
     14 

~/miniforge3/envs/hidrologia/lib/python3.8/site-packages/pyswmm/swmm5.py in <module>
     18 
     19 # Third party imports
---> 20 from swmm.toolkit import solver
     21 
     22 # Local imports

~/miniforge3/envs/hidrologia/lib/python3.8/site-packages/swmm/toolkit/solver.py in <module>
     16 # Import the low-level C/C++ module
     17 if __package__ or "." in __name__:
---> 18     from . import _solver
     19 else:
     20     import _solver

ImportError: libswmm5.so: cannot open shared object file: No such file or directory
```

Ubuntu 20.10, in a conda env, pyswmm 1.0.1 installed with pip.

**Comment by jennwuu** [comment]
I think this issue should be addressed soon by this upcoming PR: https://github.com/OpenWaterAnalytics/swmm-python/pull/73 

CC: @michaeltryby

**Comment by michaeltryby** [comment]
@lrntct did you activate the conda environment prior to using it? Won’t work unless you activate first.

**Comment by michaeltryby** [comment]
@lrntct if you are running on Ubuntu you must have built the SWMM-toolkit wheel yourself. Did you note any warnings or errors  during the wheel build?

**Comment by michaeltryby** [comment]
@lrntct if you are interested in helping us beta test you could try our latest updated wheel found here

https://github.com/OpenWaterAnalytics/swmm-python/actions/runs/861547006

**Comment by lrntct** [comment]
It seems that there where something strange in my conda env, because I somehow managed to install pyswmm with pip. I created a new env and installation with pip failed, indeed. I installed the latest wheel from your link @michaeltryby, and it solved this import issue.

**Comment by michaeltryby** [comment]
@lrntct I’m glad it worked for you! I will go ahead and close the issue.
