### ISSUE TITLE
Proposal to relicense swmm-toolkit from CC0 to CC BY 4.0

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/swmm-python#89]
If you are a contributor or user of the packages found here please consider the implications of relicensing on your work and feel free to comment here. Thank you for supporting our project!

**Comment by jennwuu** [comment]
I support the relicensing effort.

**Comment by michaeltryby** [comment]
Link to CC BY 4.0 License
https://creativecommons.org/licenses/by/4.0/

**Comment by michaeltryby** [comment]
Please see PR #90 for details.

**Comment by karosc** [comment]
who doesn't want to be acknowledged, right? That seems to be the major difference between the licenses from what I can find.

**Comment by michaeltryby** [comment]
So I've been thinking through the implications of the relicense ... If we go through with it, CC BY 4.0 is only going to apply to new work in releases going forward. This is because the majority of work has already been released public domain/CC0. 

There is another route we can go. Right now we dynamic link to OWA/SWMM and bundle the library. If we were to static link OWA/SWMM, its licensing terms would supersede those for this project. So in other words OWA/SWMM's license would apply here instead of public/domain/CC0. 

The later approach would totally cover the project with OWA/SWMM License. Where as if we relicense, the vast majority of the project would remain public domain/CC0. 

Definitely, something to think about as we continue to weigh our options. Thoughts?

**Comment by jennwuu** [comment]
What is dynamic link vs static link of OWA/SWMM?

**Comment by michaeltryby** [comment]
Hey @jennwuu, there are two ways of linking objects static linking and dynamic linking. When the compiler creates an executable linking the object files together into an executable it is static linking them together. So static linking is something you should already be familiar with. 

If you look at the contents of the swmm-toolkit wheel it contains two dynamic libraries. One _toolkit* is the wrapper generated by SWIG, and the other is SWMM5. We took great care to set up the wheel so the two libraries can find each other at runtime. They are separate libraries with separate licenses. 

On the other hand, if we were to static link the two the compiler would combine _toolkit* and SWMM5 to produce a single library. Static linking functionally and legally binds the libraries together. Swmm5’s more restrictive license would supersede the current swmm-toolkit license.

**Comment by jennwuu** [comment]
Hi @michaeltryby. Thanks for the detailed explanation. Are there disadvantage using dynamic vs static? If both options are equivalent, then dynamic link sounds good to me.

**Comment by abhiramm7** [comment]
@karosc and @michaeltryby, do we still need this issue?
