### ISSUE TITLE
Add unit test for get_system_attribute and investigate seg fault error when using this function

### ISSUE THREAD

**Issue by jennwuu** [OpenWaterAnalytics/swmm-python#91]

**Comment by karosc** [comment]
@jennwuu , I may have jumped the gun on this one. But check: 

[https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/350](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/350)

**Comment by jennwuu** [comment]
oooh nice! let me review your PR and get back to you. Awesome!

**Comment by karosc** [comment]
@jennwuu, we can close this now 👍🏻
