### ISSUE TITLE
Deprecate Python 3.6, add support for Python 3.10

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/swmm-python#95]
Python 3.6 reached end of life 12/2021. Time to deprecate it and add support for Python 3.10

**Comment by abhiramm7** [comment]
Handled by @karosc in https://github.com/OpenWaterAnalytics/swmm-python/blob/34f504e5019fbfd01c6a7ff0931cc66d89fe7128/.github/workflows/python-package.yml#L75.
